---
- name: Deploy SentinelOne Agent
  hosts: servers
  become: yes
  tasks:
    - name: Copy SentinelOne Agent .deb file to servers
      copy:
        src: /path/to/SentinelAgent_linux_x86_64_v24_1_2_6.deb
        dest: /path/to/destination/SentinelAgent_linux_x86_64_v24_1_2_6.deb
      mode: '0644'
